## Analyze Code ##################################################################
analyze:
	jscs . --fix --config=node_modules/bdsft-sdk-core/.jscsrc && jshint . --config=node_modules/bdsft-sdk-core/.jshintrc --exclude-path=node_modules/Library-SDK-Core/.jshintignore --verbose
